{% set name = "dbt-spark" %}
{% set version = "1.10.2" %}

# E   ModuleNotFoundError: No module named 'pyhive>=0.7'
# All tests failed with
# E   dbt_common.exceptions.base.DbtRuntimeError: Runtime Error
# E   http connection method requires additional dependencies.
# E   Install the additional required dependencies with `pip install dbt-spark[PyHive]`
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 826e823b3a0bce5ba60e6315a42880c07553ae1a09efcf820d082c5980af2619

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310 or py>313]  # dbt-common has no py314+ builds in main yet

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - dbt-common >=1.10,<2.0
    - dbt-adapters >=1.7,<2.0
    - dbt-core >=1.8.0rc1,<2.0
    - sqlparams >=3.0.0
  run_constrained:
    - pyodbc >=5.1,<5.3
    - PyHive >=0.7.0,<0.8.dev0
    - thrift >=0.11.0,<0.17.0
    - pyspark >=3.0.0,<5.0.0
    - sqlparse >=0.4.2  # not directly required, pinned by Snyk to avoid a vulnerability

test:
  imports:
    - dbt.adapters.spark
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-adapters/blob/main/dbt-spark
  summary: The Apache Spark adapter plugin for dbt
  license: Apache-2.0
  license_family: Apache
  license_file: License.md
  description: |
    dbt-spark enables dbt to work with Apache Spark.
  dev_url: https://github.com/dbt-labs/dbt-spark
  doc_url: https://github.com/dbt-labs/dbt-adapters/blob/main/dbt-spark/README.md

extra:
  recipe-maintainers:
    - rxm7706
    - monaldoj
